updates:
  - assignees:
      - ffflorian
    commit-message:
      prefix: ci(deps)
    cooldown:
      default-days: 5
      exclude:
        - ffflorian/*
    directory: /
    open-pull-requests-limit: 99
    package-ecosystem: github-actions
    schedule:
      interval: weekly
version: 2
